name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy FE via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/fevnpay
            git fetch origin staging
            git checkout staging
            git pull origin staging
            yarn
            yarn build
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
